### ISSUE TITLE
Is there a way for increase screen resolution?

### ISSUE THREAD

**Issue by CSharpLover** [smaffer/vgax#1]
Hi, i'm using this library with my Arduino Uno for my Homemade Computer project. Can i increase screen resolution with converting this library to monochrome? Black and white enough for me, i just need to increase screen resolution.

//Edit: I wrote increase wrong, I saw it now.

**Comment by smaffer** [comment]
Hi CSharpLovel. Great project! 
The library can be modified to use only 1bit for pixel but the horizontal resolution cannot be easily increased. Is possible to increase the height to reach 120px, using the same amount of SRAM of the original code. To do thats you must modify or rewrite some of the code. Keep in mind that all the drawing methods (blit, blitmask, clear, etc) must be modified to work with 1bit per pixel instead of 2bit per pixel.
If you want, you can use the original Nick Gammon's code (http://www.gammon.com.au/forum/?id=11608) that reach 160px horizontal pixels. This is the code from i have started to write VGAX.
